# Generated by Django 3.2.13 on 2023-04-07 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.CharField(default='dd', error_messages={'unique': 'This email has already been registered.'}, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='password',
            field=models.CharField(default='dd', max_length=200),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(default=12, error_messages={'unique': 'This number has already been registered.'}, max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='username',
            field=models.CharField(default='dd', error_messages={'unique': 'This username has already been registered.'}, max_length=20, unique=True),
        ),
    ]
